# Generated by Django 2.0.5 on 2018-05-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_restaurants', to='restaurants.Tag'),
        ),
    ]
