# Generated by Django 2.0.5 on 2018-05-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20180528_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
