# Generated by Django 2.0.5 on 2018-06-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20180530_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='ordermenutransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SERVED', 'Served'), ('CANCELED', 'Canceled')], default='PENDING', max_length=8),
        ),
    ]
