# Generated by Django 2.0.5 on 2018-06-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20180602_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermenutransaction',
            name='served_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
